# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /frontend

RUN npm config set registry http://registry.npmjs.org/

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

# Build the React Vite app
RUN npm run build

# Install a lightweight web server to serve the build files
RUN npm install -g serve

# Expose the port your app runs on
EXPOSE 3000

# Command to serve the React app
CMD ["serve", "-s", "dist"]