# Use Node.js image
FROM node:latest

# Set working directory
WORKDIR /app

RUN npm config set registry http://registry.npmjs.org/

# Clear NPM cache to avoid install issues
RUN npm cache clean --force

# Install project dependencies with legacy peer deps
RUN npm install --legacy-peer-deps --prefer-offline --no-audit

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy all source code
COPY . .

# Expose port 5000
EXPOSE 5000

# Start the app with nodemon
CMD ["nodemon", "-L", "index.js"]
