# Use Node.js image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally (for development only)
RUN npm install -g nodemon

# Copy all source code
COPY . .

# Set environment variables (build-time)
ARG MONGO_URI
ARG CLERK_WEBHOOK_SECRET
ARG CLERK_PUBLISHABLE_KEY
ARG CLERK_SECRET_KEY
ARG CLIENT_URL
ARG IK_URL_ENDPOINT
ARG IK_PUBLIC_KEY
ARG IK_PRIVATE_KEY

# Convert them to runtime ENV variables
ENV MONGO_URI=$MONGO_URI
ENV CLERK_WEBHOOK_SECRET=$CLERK_WEBHOOK_SECRET
ENV CLERK_PUBLISHABLE_KEY=$CLERK_PUBLISHABLE_KEY
ENV CLERK_SECRET_KEY=$CLERK_SECRET_KEY
ENV CLIENT_URL=$CLIENT_URL
ENV IK_URL_ENDPOINT=$IK_URL_ENDPOINT
ENV IK_PUBLIC_KEY=$IK_PUBLIC_KEY
ENV IK_PRIVATE_KEY=$IK_PRIVATE_KEY

# Expose port 5000
EXPOSE 5000

# Start the app with nodemon
CMD ["nodemon", "-L", "index.js"]
