# Use Node.js image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy all source code
COPY . .

# Expose port 5000
EXPOSE 5000

# Start the app with nodemon
CMD ["nodemon", "-L", "index.js"]
