- name: Deploy Blog Application
  hosts: ec2
  become: yes
  tasks:
    - name: Pull Backend Docker Image
      shell: docker pull nimeshayasith/backend:latest

    - name: Pull Frontend Docker Image
      shell: docker pull nimeshayasith/frontend:latest

    - name: Stop running backend container
      shell: docker stop backend || true && docker rm backend || true
      ignore_errors: yes

    - name: Stop running frontend container
      shell: docker stop frontend || true && docker rm frontend || true
      ignore_errors: yes

    - name: Run Backend Container
      shell: docker run -d -p 5000:5000 --name backend nimeshayasith/backend:latest

    - name: Run Frontend Container
      shell: docker run -d -p 5173:5173 --name frontend nimeshayasith/frontend:latest