- hosts: ec2
  become: yes
  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes
